"""Guard 1/2 (B0, staged BEFORE the ``Finding.not_applicable`` migration): every real
config's ``(finding id, fingerprint)`` set stays byte-for-byte stable across a release.

WHY THIS EXISTS. ``baseline.fingerprint()`` (``clawseccheck/baseline.py:37-41``) hashes
``sha1(finding.detail)[:8]`` -- and that exact ``<id>:<8-hex>`` shape is what a real
user's own ``.clawseccheckignore`` names when they suppress a specific finding rather
than a whole check id (``baseline.apply()``). If a later change edits so much as one
character of some check's ``detail`` text -- even in a branch only one obscure fixture
happens to exercise -- every user who suppressed that exact finding by fingerprint is
silently UN-suppressed on their next run: no error, no warning, the finding just
reappears on their dashboard as if newly discovered. That is a false PASS-by-omission
in reverse: a real, previously-triaged finding starts looking like a fresh regression.

Until now this was checked at review time, by eye, for whatever lines a diff happened to
touch. This test makes it a CI-enforced invariant instead: it drives the real
``audit()`` over the ENTIRE fixture corpus, computes the exact
``sorted((f.id, baseline.fingerprint(f)) for f in findings)`` a real
``.clawseccheckignore`` could be keyed against, and diffs it against a manifest
committed alongside this file (``finding_fingerprint_manifest.txt``).

THE INVARIANT THIS PINS FOR THE LATER MIGRATION: ``Finding.detail`` strings stay
byte-for-byte unchanged. A part-B change that needs to reword a ``detail`` string is a
deliberate, separately-announced wording release (see ``baseline.py``'s own module
docstring) -- never a silent side effect of adding/reading ``Finding.not_applicable``.

Regenerate ONLY for such a deliberate, announced change:
    python3 tests/test_finding_fingerprint_manifest.py --write

That re-derives every line from the real, current ``audit()`` output using the exact
same helpers this file's tests assert against -- generator and guard can never drift
apart because they are the same code.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

from clawseccheck import audit, baseline

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
MANIFEST = Path(__file__).resolve().parent / "finding_fingerprint_manifest.txt"

_HEADER = (
    "# GENERATED by test_finding_fingerprint_manifest.py --write. Do not hand-edit.\n"
    "# One line per fixture home: <relpath-under-fixtures>\\t<id1>:<fp1>,<id2>:<fp2>,...\n"
    "# Regenerate ONLY for a deliberate, announced Finding.detail wording release.\n"
)


# Not real fixture homes: `fixtures/conftest.py` (see its own docstring) is imported by
# pytest during collection purely for its `collect_ignore_glob`, which byte-compiles it
# into a `__pycache__/` sibling as a side effect -- present or absent depending on
# collection order and filesystem state, never a committed fixture. Auditing it as a
# "home" would make the corpus (and this guard's membership) collection-order-dependent.
_NOT_A_FIXTURE = {"__pycache__"}


def _corpus_targets() -> list[Path]:
    """Every fixture home in the corpus, plus each fixture's nested ``openclaw_home/``
    variant where present -- mirrors ``tests/test_b315_unscored_never_fails.py``'s own
    corpus discovery so both full-corpus structural guards exercise the identical set,
    minus the non-fixture artifact directories named in ``_NOT_A_FIXTURE`` above.
    """
    homes = sorted(
        d for d in FIXTURES.iterdir()
        if d.is_dir() and not d.name.startswith(".") and d.name not in _NOT_A_FIXTURE
    )
    targets: list[Path] = []
    for h in homes:
        targets.append(h)
        nested = h / "openclaw_home"
        if nested.is_dir():
            targets.append(nested)
    return targets


CORPUS = _corpus_targets()


def _fingerprint_pairs(home: Path) -> list[tuple[str, str]]:
    """The exact per-fixture value this guard pins: every ``(id, fingerprint)`` pair a
    real ``.clawseccheckignore`` on this exact config could be keyed on. Sort key
    matches the task's own formula, ``sorted((f.id, baseline.fingerprint(f)) for f in
    ...)`` -- note ``baseline.fingerprint()`` already returns the ``<id>:<hash>`` shape
    (``baseline.py``'s own ``fingerprint()`` docstring), so ``f.id`` here is only the
    sort key, never re-embedded in the encoded manifest text (see ``_encode_pairs``)."""
    _, findings, _ = audit(home)
    return sorted((f.id, baseline.fingerprint(f)) for f in findings)


def _encode_pairs(pairs: list[tuple[str, str]]) -> str:
    # Each fingerprint string already IS "<id>:<hash>" -- storing f.id again alongside
    # it would just duplicate the id in every manifest entry for no benefit.
    return ",".join(fp for _fid, fp in pairs)


def _manifest_line(home: Path) -> str:
    rel = str(home.relative_to(FIXTURES))
    return f"{rel}\t{_encode_pairs(_fingerprint_pairs(home))}"


def _load_manifest() -> dict[str, str]:
    entries: dict[str, str] = {}
    for raw in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = raw.strip("\n")
        if not line or line.startswith("#"):
            continue
        rel, _, pairs = line.partition("\t")
        entries[rel] = pairs
    return entries


def _write_manifest() -> None:
    lines = [_manifest_line(h) for h in CORPUS]
    MANIFEST.write_text(_HEADER + "\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------------------
# Sanity: the corpus and the committed manifest cannot silently drift apart in MEMBERSHIP
# (a stale/incomplete manifest would make the per-fixture guard below vacuous for
# whatever fixture went missing from it).
# ---------------------------------------------------------------------------------------

def test_corpus_is_non_empty():
    assert len(CORPUS) >= 400, "expected the full fixtures/ corpus (480+ homes)"


def test_manifest_file_exists():
    assert MANIFEST.is_file(), (
        f"{MANIFEST} is missing -- the committed fingerprint baseline this guard "
        "compares against must exist and be checked in alongside this test"
    )


def test_manifest_covers_the_full_corpus():
    committed = _load_manifest()
    corpus_rels = {str(h.relative_to(FIXTURES)) for h in CORPUS}
    missing = corpus_rels - set(committed)
    stale = set(committed) - corpus_rels
    assert not missing and not stale, (
        f"the committed manifest and the live fixture corpus disagree on membership -- "
        f"missing from manifest: {sorted(missing)[:10]}; "
        f"stale entries no longer in the corpus: {sorted(stale)[:10]}; "
        "regenerate with 'python3 tests/test_finding_fingerprint_manifest.py --write'"
    )


# ---------------------------------------------------------------------------------------
# THE GUARD. Parametrized per fixture (matches test_b315_unscored_never_fails.py's own
# full-corpus style) so a CI failure names exactly which fixture -- and, via the
# diagnostic below, exactly which check id -- had its fingerprint move.
# ---------------------------------------------------------------------------------------

@pytest.mark.parametrize("home", CORPUS, ids=lambda p: str(p.relative_to(FIXTURES)))
def test_fingerprints_match_the_committed_manifest(home):
    """A changed fingerprint here means some check's ``Finding.detail`` text changed on
    this exact fixture -- which orphans any real user's ``.clawseccheckignore``
    fingerprint entry for that finding, silently (see module docstring). This is the
    load-bearing assertion; the membership tests above only guard against a stale or
    incomplete manifest making this one vacuous.
    """
    committed = _load_manifest()
    rel = str(home.relative_to(FIXTURES))
    want = committed.get(rel)
    assert want is not None, f"{rel} is not in the committed manifest"

    got_pairs = _fingerprint_pairs(home)
    got = _encode_pairs(got_pairs)
    if got == want:
        return

    want_pairs = dict(p.split(":", 1) for p in want.split(",") if p)
    got_by_id = dict(got_pairs)
    changed = sorted(
        fid for fid in set(got_by_id) | set(want_pairs)
        if got_by_id.get(fid) != want_pairs.get(fid)
    )
    pytest.fail(
        f"{rel}: finding fingerprint(s) changed for {changed} -- if this is a "
        "deliberate, announced Finding.detail wording change, regenerate the manifest "
        "('python3 tests/test_finding_fingerprint_manifest.py --write'); otherwise a "
        "check's detail text drifted unintentionally and will silently orphan real "
        "users' .clawseccheckignore fingerprint suppressions"
    )


if __name__ == "__main__":  # pragma: no cover
    if "--write" in sys.argv:
        _write_manifest()
        print(f"wrote {MANIFEST} ({len(CORPUS)} fixture(s))")
    else:
        pytest.main([__file__, "-q"])
