"""The generated check catalogue must never ship Python source as security advice.

WHY THIS FILE EXISTS
--------------------
``docs/CHECKS.md`` is generated by ``scripts/gen_checks_docs.py``, which reads each check's
``fix=`` / ``why=`` expression out of the AST and renders it. When the expression is a plain
string it renders prose. When it is anything else, the generator used to fall back to
``ast.unparse`` — and a document has no run to substitute values from, so what reached the
page was code.

This has now happened twice, and the second time nothing caught it:

    RISK-15   "...with an explicit _key_advice(ctx, 'browser.ssrfPolicy.hostnameAllowlist',
              ...)"                     — caught only because markdownlint read the
                                          underscore as emphasis (B-738)
    RISK-23   "This install has str(len(fired)) independent persistence mechanisms ...
              from different mechanism classes: '; '.join(fired)"
              "Investigate every flagged anchor, starting with '; '.join(signal_bearing)"
                                        — no underscore, so nothing objected

B-738's response was to special-case the one callee. That is what let the second one
through, so the fallback itself was changed instead: an expression containing a CALL renders
as an ellipsis. A bare name is left alone deliberately — in the schematic ``Chain:`` lines
``channel_label -> tool_label -> host / filesystem`` tells a reader what fills each position,
and eliding it would trade a cosmetic problem for a worse one.

This file is the closure over that class. It does not name RISK-15 or RISK-23: it renders the
WHOLE catalogue and requires that no user-facing line looks like source, so the third instance
fails the build instead of shipping.

Offline, read-only, stdlib only.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
GENERATOR = REPO / "scripts" / "gen_checks_docs.py"
SHIPPED = REPO / "docs" / "CHECKS.md"

#: Shapes that only appear in Python source, never in a sentence written for a person.
#: Each is anchored on the syntax rather than on a known callee — naming callees is exactly
#: the mistake this file exists to stop repeating.
_SOURCE_SHAPES = (
    re.compile(r"\.join\("),
    re.compile(r"\b(?:str|len|repr|sorted|getattr|isinstance)\("),
    re.compile(r"\bf['\"]"),
    # An identifier ABUTTING an open paren. The discriminator is the space: prose writes
    # "active (untrusted input, private data)" and code writes "_key_advice(ctx, ...)".
    # An earlier version allowed whitespace between them and convicted that very sentence —
    # caught by this file's own false-positive control, which is why that control exists.
    # ...but NOT `exec()` / `eval()`, which the catalogue names in prose when describing what
    # a malicious skill does, and NOT the "skill(s)" / "surface(s)" plural idiom. Both were
    # convicted by a first version of this pattern; excluding an empty paren and a bare "(s)"
    # separates them from a real call without weakening it — `_key_advice(ctx, ...)` and
    # `str(len(fired))` still match.
    re.compile(r"[A-Za-z_][A-Za-z0-9_]*\((?!s\)|\))"),
)

#: Lines that legitimately contain code, and are not advice. The catalogue quotes config keys
#: and CLI invocations on purpose; those are what a reader is meant to type.
_CODE_BEARING_PREFIXES = ("- Config:", "- Flag:", "    ", "\t", "```", "|")


def _generated() -> str:
    proc = subprocess.run(
        [sys.executable, str(GENERATOR)],
        cwd=REPO, capture_output=True, text=True, timeout=600,
    )
    assert proc.returncode == 0, proc.stderr[-2000:]
    assert proc.stdout.strip(), "the generator produced nothing"
    return proc.stdout


def _offending(text: str) -> list[str]:
    out = []
    for line in text.splitlines():
        if not line.strip() or line.startswith(_CODE_BEARING_PREFIXES):
            continue
        if any(p.search(line) for p in _SOURCE_SHAPES):
            out.append(line.strip())
    return out


def test_the_generated_catalogue_contains_no_python_source():
    offenders = _generated()
    bad = _offending(offenders)
    assert not bad, (
        "the generated check catalogue would ship Python source as security advice — a "
        "reader is told to act on something that is machinery, not instruction:\n  "
        + "\n  ".join(bad)
    )


def test_the_shipped_catalogue_matches_the_generator():
    """``docs/CHECKS.md`` is generated; a stale copy is how a fixed leak keeps shipping."""
    assert SHIPPED.read_text(encoding="utf-8") == _generated(), (
        "docs/CHECKS.md differs from a fresh run of scripts/gen_checks_docs.py — "
        "regenerate it with `python3 scripts/gen_checks_docs.py --write`"
    )


@pytest.mark.parametrize("sample", [
    "  Investigate every flagged anchor, starting with '; '.join(signal_bearing) — then review",
    "  This install has str(len(fired)) independent persistence mechanisms flagged at once,",
    "  ...with an explicit _key_advice(ctx, 'browser.ssrfPolicy.hostnameAllowlist', ...)",
])
def test_the_detector_would_have_caught_both_real_leaks(sample):
    """A control on the control.

    The two real leaks are fixed, so the sweep above passes over a clean catalogue — which it
    would also do if the patterns matched nothing at all. These are the exact lines that
    shipped; the detector must convict them.
    """
    assert _offending(sample), f"the detector does not catch a line that really shipped: {sample!r}"


def test_prose_that_merely_mentions_a_function_is_not_convicted():
    """The other direction: the detector must not fire on ordinary advice.

    Without this, the cheapest way to keep the build green would be to make the patterns so
    broad that nobody can write a sentence, and the file would be quietly disabled.
    """
    innocent = [
        "  Set gateway.bind to 127.0.0.1 and restart the agent.",
        "  Review every skill you did not write yourself, then re-run the audit.",
        "  Two of three legs are active (untrusted input, private data) — close one.",
        "  Remove the plugin, or add it to the allowlist if you trust its author.",
    ]
    for line in innocent:
        assert not _offending(line), f"ordinary advice was convicted as source: {line!r}"
