"""B-025 & B-026: Tailored remediation prose for B3 (least privilege) and B4 (sandbox).

Asserts that fix strings generated by check_least_privilege (B3) and check_sandbox (B4)
only name triggers that actually fired for the given configuration.
"""
from __future__ import annotations

from pathlib import Path

from clawseccheck.catalog import FAIL, WARN
from clawseccheck.checks import check_least_privilege, check_sandbox
from clawseccheck.collector import Context


def _ctx(cfg: dict) -> Context:
    c = Context(home=Path("/nonexistent"))
    c.config = cfg
    c.include_host = True
    return c


# ===========================================================================
# B3: Least privilege fix tests (B-025)
# ===========================================================================

def test_b3_wildcard_allowfrom_only_fix():
    cfg = {
        "tools": {"elevated": {"allowFrom": "*"}},
        "plugins": {"allow": ["some-plugin"]},  # plugins.allow is already defined!
    }
    f = check_least_privilege(_ctx(cfg))
    assert f.status == FAIL
    assert "Restrict tools.elevated.allowFrom" in f.fix
    assert "plugins.allow" not in f.fix
    assert "tools.profile" not in f.fix


def test_b3_profile_only_fix():
    cfg = {
        "tools": {"profile": "coding", "elevated": {"allowFrom": {"tg": ["123"]}}},
        "plugins": {"allow": ["some-plugin"]},
    }
    f = check_least_privilege(_ctx(cfg))
    assert f.status == WARN
    assert "Set tools.profile to 'minimal'" in f.fix
    assert "tools.elevated" not in f.fix
    assert "plugins.allow" not in f.fix


def test_b3_missing_plugins_allow_only_fix():
    cfg = {
        "tools": {"profile": "minimal", "elevated": {"allowFrom": {"tg": ["123"]}}},
        "plugins": {"entries": {"myplugin": {}}},
    }
    f = check_least_privilege(_ctx(cfg))
    assert f.status == WARN
    assert "Define a plugins.allow array" in f.fix
    assert "tools.elevated" not in f.fix
    assert "tools.profile" not in f.fix


# ===========================================================================
# B4: Sandbox fix tests (B-026)
# ===========================================================================

def test_b4_mode_off_only_fix():
    # Only sandbox mode is off, no docker binds/network configured.
    cfg = {
        "agents": {"defaults": {"sandbox": {"mode": "off"}}}
    }
    f = check_sandbox(_ctx(cfg))
    assert f.status == FAIL
    assert "Set agents.defaults.sandbox.mode" in f.fix
    assert "docker.network" not in f.fix
    assert "docker.binds" not in f.fix
    assert "workspaceAccess" not in f.fix


def test_b4_mode_off_and_network_host_fix():
    cfg = {
        "agents": {"defaults": {"sandbox": {"mode": "off", "docker": {"network": "host"}}}}
    }
    f = check_sandbox(_ctx(cfg))
    assert f.status == FAIL
    assert "Set agents.defaults.sandbox.mode" in f.fix
    assert "Set agents.defaults.sandbox.docker.network" in f.fix
    assert "docker.binds" not in f.fix
    assert "workspaceAccess" not in f.fix


def test_b4_mode_off_and_workspace_rw_fix():
    cfg = {
        "agents": {"defaults": {"sandbox": {"mode": "off", "workspaceAccess": "rw"}}}
    }
    f = check_sandbox(_ctx(cfg))
    assert f.status == FAIL
    assert "Set agents.defaults.sandbox.mode" in f.fix
    assert "Set workspaceAccess" in f.fix
    assert "docker.network" not in f.fix
    assert "docker.binds" not in f.fix


def test_b4_mode_off_and_docker_sock_fix():
    cfg = {
        "agents": {"defaults": {"sandbox": {
            "mode": "off",
            "docker": {"binds": ["/var/run/docker.sock:/var/run/docker.sock"]}
        }}}
    }
    f = check_sandbox(_ctx(cfg))
    assert f.status == FAIL
    assert "Set agents.defaults.sandbox.mode" in f.fix
    assert "Remove the docker.sock bind" in f.fix
    assert "Remove broad host path binds" in f.fix
    assert "docker.network" not in f.fix
    assert "workspaceAccess" not in f.fix
