#!/usr/bin/env python3
"""Dev-only regenerator for clawseccheck/curlgrammar.py's OPTION_ARITY /
SHORT_TO_LONG / category tables (CLAWSECCHECK-B-986).

NEVER imported by clawseccheck itself -- this is a one-off developer tool
that talks to a real, locally installed `curl` binary to re-derive the
grammar tables from scratch. `curlgrammar.py`'s own committed data is what
ships and is what every check actually runs against; this script exists so a
future curl-version bump (or a spot-check of today's data) can be redone
soundly instead of hand-edited.

Usage:
    python3 scripts/gen_curl_grammar.py > /tmp/regenerated_tables.py

Then hand-review the diff against clawseccheck/curlgrammar.py's existing
OPTION_ARITY/SHORT_TO_LONG/_CATEGORY_* dicts before ever pasting anything in
-- OPTION_ROLE and _PROXY_DNS_CONN_SAFE_JUSTIFIED are NOT regenerated by this
script (role assignment is the human, security-relevant judgment call this
whole redesign exists to keep out of blind automation -- see curlgrammar.py's
module docstring and CLAWSECCHECK-B-986's ticket history). A newly-added curl
option always starts unassigned; the completeness test in
tests/test_curlgrammar.py will fail until a human adds it to OPTION_ROLE
(defaulting to SAFE only after actually considering whether it can redirect
the destination, same as every existing entry's comment explains).

Method (mirrors how this ticket's own oracle was captured against curl 8.5.0,
2026-09-25 -- see the ticket's scratchpad):
  1. Parse `curl --help all` for every long-option row and its short alias.
     Arity is read from the row's own `<value>`-shaped placeholder.
  2. Cross-check by RUNNING curl with each long option and no further
     argument (`curl --OPT`, nothing after): a true "value" option answers
     "requires parameter"; a true "bool" option just proceeds (and is
     immediately stopped here with no URL given, so no actual network I/O
     ever happens). This is the same differential that caught
     --haproxy-clientip and --write-out's help-text being wrong (see
     curlgrammar.py's OPTION_ARITY docstring) -- so step 2's result wins on
     any disagreement, not step 1's.
  3. Category membership is read from `--help all`'s own section headers.

No network access; no clawseccheck import. Requires `curl` on PATH.
"""
from __future__ import annotations

import re
import subprocess
import sys

_ROW_RE = re.compile(
    r"^\s*(?:-(?P<short>[A-Za-z0-9#:]), )?--(?P<long>[a-z0-9.-]+)(?P<val>\s+<[^>]+>)?\s{2,}",
)
_CATEGORY_HEADER_RE = re.compile(r"^\s*(?P<cats>[a-z][a-z, ]*[a-z]):\s*$")


def _run(*args: str) -> str:
    return subprocess.run(
        ["curl", *args], capture_output=True, text=True, timeout=10
    ).stdout


def parse_help_all(text: str) -> dict:
    """Returns {long_name: {"short": short_or_None, "help_arity": "bool"|"value"}}."""
    out = {}
    for line in text.splitlines():
        m = _ROW_RE.match(line)
        if not m:
            continue
        long_name = "--" + m.group("long")
        short = ("-" + m.group("short")) if m.group("short") else None
        arity = "value" if m.group("val") else "bool"
        out[long_name] = {"short": short, "help_arity": arity}
    return out


def empirical_arity(long_name: str) -> str:
    """Feed *long_name* with no further argument; curl's own complaint tells
    us whether it wanted one. Never supplies a URL, so nothing is requested
    even for a genuine value-taking option that would otherwise proceed."""
    proc = subprocess.run(
        ["curl", long_name], capture_output=True, text=True, timeout=5
    )
    err = (proc.stderr or "") + (proc.stdout or "")
    if "requires parameter" in err:
        return "value"
    if "is unknown" in err:
        return "unknown"  # not a real option on this build -- caller should skip
    return "bool"


def main() -> int:
    version_line = _run("--version").splitlines()[0] if _run("--version") else ""
    help_text = _run("--help", "all")
    if not help_text:
        print("error: `curl --help all` produced no output", file=sys.stderr)
        return 1
    parsed = parse_help_all(help_text)

    print(f'# curl --version: {version_line}')
    print("OPTION_ARITY = {")
    for name in sorted(parsed):
        help_arity = parsed[name]["help_arity"]
        emp = empirical_arity(name)
        arity = emp if emp != "unknown" else help_arity
        if emp != "unknown" and emp != help_arity:
            print(f"    # DISAGREEMENT: help={help_arity!r} emp={emp!r} -- verify by hand", file=sys.stderr)
        print(f"    {name!r}: {arity!r},")
    print("}")
    print()
    print("SHORT_TO_LONG = {")
    for name in sorted(parsed):
        short = parsed[name]["short"]
        if short:
            print(f"    {short[1:]!r}: {name!r},")
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
