"""B-986: curl's own option grammar, as vetted data -- not
enumeration-by-reading-the-source.

Generated from a real, executed curl 8.5.0 (Ubuntu, `curl 8.5.0
(x86_64-pc-linux-gnu) libcurl/8.5.0 ...`, Release-Date 2023-12-06), captured
2026-09-25 by `curl --help all` plus a per-option EMPIRICAL arity probe (each
of curl's 258 documented long options fed an empty-string value and observed,
not just its --help text read) -- see this ticket's scratchpad
(`arity_oracle_v2.json`/`categories.json`/`help_all_8.5.0.txt`) for the raw
capture. `scripts/gen_curl_grammar.py` documents how to redo this capture
against a live curl and re-run the same transform that produced the tables
below.

Two curl-parser facts this whole module leans on (verified directly against
the same curl 8.5.0 binary, not assumed):
  * curl does NOT support `--option=value` glued long-option syntax --
    `curl --cert=/path` errors `option --cert=/path: is unknown` (the
    parser looks up the *entire* post-`--` text, `=` included, as one
    candidate option name; nothing named that exists). `curlargv.py`
    therefore never splits on `=`.
  * curl accepts an unambiguous PREFIX of a long option name in place of the
    full spelling (`--noprox` resolves to `--noproxy` because no other option
    starts with `noprox`). `curlargv.py` implements this via `OPTION_ARITY`/
    `OPTION_ROLE`'s own keys as the candidate set.

Every option gets exactly ONE role from the closed set below -- SAFE is an
explicit, deliberate member of that set (not a silent default with no
guard): `OPTION_ROLE` is total over every key of `OPTION_ARITY` (see
`test_curlgrammar.py`'s completeness test), and every value-taking option in
curl's own proxy/dns/connection `--help` categories that ISN'T HOP is
required (by the same test) to be a member of `_PROXY_DNS_CONN_SAFE_JUSTIFIED`
below, whose comment carries the justification.
"""
from __future__ import annotations

CURL_VERSION = "8.5.0"
GENERATED = "2026-09-25"

# --------------------------------------------------------------------------
# The closed role set. HOP is the only role decision-1 (B-986) makes
# unconditional: any option with this role anywhere on a curl command line
# refuses the B-415 in-cluster-auth exemption, full stop, regardless of the
# scheme carried by whatever DEST word is also present.
# --------------------------------------------------------------------------
ROLE_DEST = "DEST"  # value is curl's own request URL (--url; bare positionals too)
ROLE_HOP = "HOP"  # value is a network hop: proxy/socks/preproxy/connect-to/
# resolve/dns-*/doh-url/unix-socket/ipfs-gateway
ROLE_CONFIG = "CONFIG"  # opaque option input read from elsewhere (-K/--config)
ROLE_AUTH_HEADER = "AUTH_HEADER"  # -H/--header
ROLE_TLS_MATERIAL = "TLS_MATERIAL"  # local key/cert files, incl. --proxy-* variants
ROLE_MIRROR = "MIRROR"  # -v/--trace*/--libcurl/--stderr
ROLE_NEXT = "NEXT"  # -:/--next -- starts a new curl "operation"
ROLE_TERMINAL = "TERMINAL"  # --help/--version/--manual -- curl exits, never requests
ROLE_SAFE = "SAFE"  # everything else -- deliberate, not a fallback-by-omission

ROLES = frozenset(
    {
        ROLE_DEST,
        ROLE_HOP,
        ROLE_CONFIG,
        ROLE_AUTH_HEADER,
        ROLE_TLS_MATERIAL,
        ROLE_MIRROR,
        ROLE_NEXT,
        ROLE_TERMINAL,
        ROLE_SAFE,
    }
)

# --------------------------------------------------------------------------
# OPTION_ARITY: "bool" (no value consumed) or "value" (consumes the next
# shell word, or a glued/clustered short-opt suffix, as its argument).
#
# Sourced from curl's own `--help all` text EXCEPT four corrections, each
# independently confirmed by running curl 8.5.0 directly (not inferred):
#   --haproxy-clientip and --write-out: help text under-reports these as
#     bool-shaped in the raw --help rows this oracle was built from, but
#     `curl --write-out` / `curl --haproxy-clientip` (no further argument)
#     both error "requires parameter" -- both are real value options.
#   --next: help text and an empirical misuse-error both looked ambiguous
#     ("option --next: is badly used here"), but that error is
#     "missing URL before --next" (--next needs a *preceding* URL, not an
#     argument of its own) -- confirmed by `curl --url A --next --url B`
#     succeeding with --next consuming zero words. bool.
#   --metalink: this curl build has metalink support compiled out ("--metalink
#     is disabled"), so its true arity can't be verified on this binary. Left
#     "bool" (curl's own --help text says so) -- if that is ever wrong, the
#     failure mode is SAFE for this module's purpose: a value mistaken for
#     bool only makes the next real word look like an *extra* apparent
#     word (DEST-count goes up, never down), which can only make the B-415
#     exemption MORE likely to refuse, never less.
#   --help/--manual/--version: real arity is moot (curl exits before normal
#     parsing) -- pinned to "bool" here for the same safe-swallow reason.
# --------------------------------------------------------------------------
OPTION_ARITY = {
    "--abstract-unix-socket": "value",
    "--alt-svc": "value",
    "--anyauth": "bool",
    "--append": "bool",
    "--aws-sigv4": "value",
    "--basic": "bool",
    "--ca-native": "bool",
    "--cacert": "value",
    "--capath": "value",
    "--cert": "value",
    "--cert-status": "bool",
    "--cert-type": "value",
    "--ciphers": "value",
    "--compressed": "bool",
    "--compressed-ssh": "bool",
    "--config": "value",
    "--connect-timeout": "value",
    "--connect-to": "value",
    "--continue-at": "value",
    "--cookie": "value",
    "--cookie-jar": "value",
    "--create-dirs": "bool",
    "--create-file-mode": "value",
    "--crlf": "bool",
    "--crlfile": "value",
    "--curves": "value",
    "--data": "value",
    "--data-ascii": "value",
    "--data-binary": "value",
    "--data-raw": "value",
    "--data-urlencode": "value",
    "--delegation": "value",
    "--digest": "bool",
    "--disable": "bool",
    "--disable-eprt": "bool",
    "--disable-epsv": "bool",
    "--disallow-username-in-url": "bool",
    "--dns-interface": "value",
    "--dns-ipv4-addr": "value",
    "--dns-ipv6-addr": "value",
    "--dns-servers": "value",
    "--doh-cert-status": "bool",
    "--doh-insecure": "bool",
    "--doh-url": "value",
    "--dump-header": "value",
    "--egd-file": "value",
    "--engine": "value",
    "--etag-compare": "value",
    "--etag-save": "value",
    "--expect100-timeout": "value",
    "--fail": "bool",
    "--fail-early": "bool",
    "--fail-with-body": "bool",
    "--false-start": "bool",
    "--form": "value",
    "--form-escape": "bool",
    "--form-string": "value",
    "--ftp-account": "value",
    "--ftp-alternative-to-user": "value",
    "--ftp-create-dirs": "bool",
    "--ftp-method": "value",
    "--ftp-pasv": "bool",
    "--ftp-port": "value",
    "--ftp-pret": "bool",
    "--ftp-skip-pasv-ip": "bool",
    "--ftp-ssl-ccc": "bool",
    "--ftp-ssl-ccc-mode": "value",
    "--ftp-ssl-control": "bool",
    "--get": "bool",
    "--globoff": "bool",
    "--happy-eyeballs-timeout-ms": "value",
    "--haproxy-clientip": "value",
    "--haproxy-protocol": "bool",
    "--head": "bool",
    "--header": "value",
    "--help": "bool",
    "--hostpubmd5": "value",
    "--hostpubsha256": "value",
    "--hsts": "value",
    "--http0.9": "bool",
    "--http1.0": "bool",
    "--http1.1": "bool",
    "--http2": "bool",
    "--http2-prior-knowledge": "bool",
    "--http3": "bool",
    "--http3-only": "bool",
    "--ignore-content-length": "bool",
    "--include": "bool",
    "--insecure": "bool",
    "--interface": "value",
    "--ipfs-gateway": "value",
    "--ipv4": "bool",
    "--ipv6": "bool",
    "--json": "value",
    "--junk-session-cookies": "bool",
    "--keepalive-time": "value",
    "--key": "value",
    "--key-type": "value",
    "--krb": "value",
    "--libcurl": "value",
    "--limit-rate": "value",
    "--list-only": "bool",
    "--local-port": "value",
    "--location": "bool",
    "--location-trusted": "bool",
    "--login-options": "value",
    "--mail-auth": "value",
    "--mail-from": "value",
    "--mail-rcpt": "value",
    "--mail-rcpt-allowfails": "bool",
    "--manual": "bool",
    "--max-filesize": "value",
    "--max-redirs": "value",
    "--max-time": "value",
    "--metalink": "bool",
    "--negotiate": "bool",
    "--netrc": "bool",
    "--netrc-file": "value",
    "--netrc-optional": "bool",
    "--next": "bool",
    "--no-alpn": "bool",
    "--no-buffer": "bool",
    "--no-clobber": "bool",
    "--no-keepalive": "bool",
    "--no-npn": "bool",
    "--no-progress-meter": "bool",
    "--no-sessionid": "bool",
    "--noproxy": "value",
    "--ntlm": "bool",
    "--ntlm-wb": "bool",
    "--oauth2-bearer": "value",
    "--output": "value",
    "--output-dir": "value",
    "--parallel": "bool",
    "--parallel-immediate": "bool",
    "--parallel-max": "value",
    "--pass": "value",
    "--path-as-is": "bool",
    "--pinnedpubkey": "value",
    "--post301": "bool",
    "--post302": "bool",
    "--post303": "bool",
    "--preproxy": "value",
    "--progress-bar": "bool",
    "--proto": "value",
    "--proto-default": "value",
    "--proto-redir": "value",
    "--proxy": "value",
    "--proxy-anyauth": "bool",
    "--proxy-basic": "bool",
    "--proxy-ca-native": "bool",
    "--proxy-cacert": "value",
    "--proxy-capath": "value",
    "--proxy-cert": "value",
    "--proxy-cert-type": "value",
    "--proxy-ciphers": "value",
    "--proxy-crlfile": "value",
    "--proxy-digest": "bool",
    "--proxy-header": "value",
    "--proxy-http2": "bool",
    "--proxy-insecure": "bool",
    "--proxy-key": "value",
    "--proxy-key-type": "value",
    "--proxy-negotiate": "bool",
    "--proxy-ntlm": "bool",
    "--proxy-pass": "value",
    "--proxy-pinnedpubkey": "value",
    "--proxy-service-name": "value",
    "--proxy-ssl-allow-beast": "bool",
    "--proxy-ssl-auto-client-cert": "bool",
    "--proxy-tls13-ciphers": "value",
    "--proxy-tlsauthtype": "value",
    "--proxy-tlspassword": "value",
    "--proxy-tlsuser": "value",
    "--proxy-tlsv1": "bool",
    "--proxy-user": "value",
    "--proxy1.0": "value",
    "--proxytunnel": "bool",
    "--pubkey": "value",
    "--quote": "value",
    "--random-file": "value",
    "--range": "value",
    "--rate": "value",
    "--raw": "bool",
    "--referer": "value",
    "--remote-header-name": "bool",
    "--remote-name": "bool",
    "--remote-name-all": "bool",
    "--remote-time": "bool",
    "--remove-on-error": "bool",
    "--request": "value",
    "--request-target": "value",
    "--resolve": "value",
    "--retry": "value",
    "--retry-all-errors": "bool",
    "--retry-connrefused": "bool",
    "--retry-delay": "value",
    "--retry-max-time": "value",
    "--sasl-authzid": "value",
    "--sasl-ir": "bool",
    "--service-name": "value",
    "--show-error": "bool",
    "--silent": "bool",
    "--socks4": "value",
    "--socks4a": "value",
    "--socks5": "value",
    "--socks5-basic": "bool",
    "--socks5-gssapi": "bool",
    "--socks5-gssapi-nec": "bool",
    "--socks5-gssapi-service": "value",
    "--socks5-hostname": "value",
    "--speed-limit": "value",
    "--speed-time": "value",
    "--ssl": "bool",
    "--ssl-allow-beast": "bool",
    "--ssl-auto-client-cert": "bool",
    "--ssl-no-revoke": "bool",
    "--ssl-reqd": "bool",
    "--ssl-revoke-best-effort": "bool",
    "--sslv2": "bool",
    "--sslv3": "bool",
    "--stderr": "value",
    "--styled-output": "bool",
    "--suppress-connect-headers": "bool",
    "--tcp-fastopen": "bool",
    "--tcp-nodelay": "bool",
    "--telnet-option": "value",
    "--tftp-blksize": "value",
    "--tftp-no-options": "bool",
    "--time-cond": "value",
    "--tls-max": "value",
    "--tls13-ciphers": "value",
    "--tlsauthtype": "value",
    "--tlspassword": "value",
    "--tlsuser": "value",
    "--tlsv1": "bool",
    "--tlsv1.0": "bool",
    "--tlsv1.1": "bool",
    "--tlsv1.2": "bool",
    "--tlsv1.3": "bool",
    "--tr-encoding": "bool",
    "--trace": "value",
    "--trace-ascii": "value",
    "--trace-config": "value",
    "--trace-ids": "bool",
    "--trace-time": "bool",
    "--unix-socket": "value",
    "--upload-file": "value",
    "--url": "value",
    "--url-query": "value",
    "--use-ascii": "bool",
    "--user": "value",
    "--user-agent": "value",
    "--variable": "value",
    "--verbose": "bool",
    "--version": "bool",
    "--write-out": "value",
    "--xattr": "bool",
}

# --------------------------------------------------------------------------
# OPTION_ROLE: total over OPTION_ARITY's keys (enforced by
# tests/test_curlgrammar.py). HOP/CONFIG/AUTH_HEADER/TLS_MATERIAL/MIRROR/
# NEXT/TERMINAL/DEST are exactly the closed, explicit allow-lists a human
# picked (see the comments above each below); SAFE is everything else.
# --------------------------------------------------------------------------
OPTION_ROLE = {
    "--abstract-unix-socket": "HOP",
    "--alt-svc": "SAFE",
    "--anyauth": "SAFE",
    "--append": "SAFE",
    "--aws-sigv4": "SAFE",
    "--basic": "SAFE",
    "--ca-native": "SAFE",
    "--cacert": "TLS_MATERIAL",
    "--capath": "TLS_MATERIAL",
    "--cert": "TLS_MATERIAL",
    "--cert-status": "SAFE",
    "--cert-type": "SAFE",
    "--ciphers": "SAFE",
    "--compressed": "SAFE",
    "--compressed-ssh": "SAFE",
    "--config": "CONFIG",
    "--connect-timeout": "SAFE",
    "--connect-to": "HOP",
    "--continue-at": "SAFE",
    "--cookie": "SAFE",
    "--cookie-jar": "SAFE",
    "--create-dirs": "SAFE",
    "--create-file-mode": "SAFE",
    "--crlf": "SAFE",
    "--crlfile": "TLS_MATERIAL",
    "--curves": "SAFE",
    "--data": "SAFE",
    "--data-ascii": "SAFE",
    "--data-binary": "SAFE",
    "--data-raw": "SAFE",
    "--data-urlencode": "SAFE",
    "--delegation": "SAFE",
    "--digest": "SAFE",
    "--disable": "SAFE",
    "--disable-eprt": "SAFE",
    "--disable-epsv": "SAFE",
    "--disallow-username-in-url": "SAFE",
    "--dns-interface": "HOP",
    "--dns-ipv4-addr": "HOP",
    "--dns-ipv6-addr": "HOP",
    "--dns-servers": "HOP",
    "--doh-cert-status": "SAFE",
    "--doh-insecure": "SAFE",
    "--doh-url": "HOP",
    "--dump-header": "SAFE",
    "--egd-file": "SAFE",
    "--engine": "SAFE",
    "--etag-compare": "SAFE",
    "--etag-save": "SAFE",
    "--expect100-timeout": "SAFE",
    "--fail": "SAFE",
    "--fail-early": "SAFE",
    "--fail-with-body": "SAFE",
    "--false-start": "SAFE",
    "--form": "SAFE",
    "--form-escape": "SAFE",
    "--form-string": "SAFE",
    "--ftp-account": "SAFE",
    "--ftp-alternative-to-user": "SAFE",
    "--ftp-create-dirs": "SAFE",
    "--ftp-method": "SAFE",
    "--ftp-pasv": "SAFE",
    "--ftp-port": "SAFE",
    "--ftp-pret": "SAFE",
    "--ftp-skip-pasv-ip": "SAFE",
    "--ftp-ssl-ccc": "SAFE",
    "--ftp-ssl-ccc-mode": "SAFE",
    "--ftp-ssl-control": "SAFE",
    "--get": "SAFE",
    "--globoff": "SAFE",
    "--happy-eyeballs-timeout-ms": "SAFE",
    "--haproxy-clientip": "SAFE",
    "--haproxy-protocol": "SAFE",
    "--head": "SAFE",
    "--header": "AUTH_HEADER",
    "--help": "TERMINAL",
    "--hostpubmd5": "SAFE",
    "--hostpubsha256": "SAFE",
    "--hsts": "SAFE",
    "--http0.9": "SAFE",
    "--http1.0": "SAFE",
    "--http1.1": "SAFE",
    "--http2": "SAFE",
    "--http2-prior-knowledge": "SAFE",
    "--http3": "SAFE",
    "--http3-only": "SAFE",
    "--ignore-content-length": "SAFE",
    "--include": "SAFE",
    "--insecure": "SAFE",
    "--interface": "SAFE",
    "--ipfs-gateway": "HOP",
    "--ipv4": "SAFE",
    "--ipv6": "SAFE",
    "--json": "SAFE",
    "--junk-session-cookies": "SAFE",
    "--keepalive-time": "SAFE",
    "--key": "TLS_MATERIAL",
    "--key-type": "SAFE",
    "--krb": "SAFE",
    "--libcurl": "MIRROR",
    "--limit-rate": "SAFE",
    "--list-only": "SAFE",
    "--local-port": "SAFE",
    "--location": "SAFE",
    "--location-trusted": "SAFE",
    "--login-options": "SAFE",
    "--mail-auth": "SAFE",
    "--mail-from": "SAFE",
    "--mail-rcpt": "SAFE",
    "--mail-rcpt-allowfails": "SAFE",
    "--manual": "TERMINAL",
    "--max-filesize": "SAFE",
    "--max-redirs": "SAFE",
    "--max-time": "SAFE",
    "--metalink": "SAFE",
    "--negotiate": "SAFE",
    "--netrc": "SAFE",
    "--netrc-file": "SAFE",
    "--netrc-optional": "SAFE",
    "--next": "NEXT",
    "--no-alpn": "SAFE",
    "--no-buffer": "SAFE",
    "--no-clobber": "SAFE",
    "--no-keepalive": "SAFE",
    "--no-npn": "SAFE",
    "--no-progress-meter": "SAFE",
    "--no-sessionid": "SAFE",
    "--noproxy": "SAFE",
    "--ntlm": "SAFE",
    "--ntlm-wb": "SAFE",
    "--oauth2-bearer": "SAFE",
    "--output": "SAFE",
    "--output-dir": "SAFE",
    "--parallel": "SAFE",
    "--parallel-immediate": "SAFE",
    "--parallel-max": "SAFE",
    "--pass": "SAFE",
    "--path-as-is": "SAFE",
    "--pinnedpubkey": "TLS_MATERIAL",
    "--post301": "SAFE",
    "--post302": "SAFE",
    "--post303": "SAFE",
    "--preproxy": "HOP",
    "--progress-bar": "SAFE",
    "--proto": "SAFE",
    "--proto-default": "SAFE",
    "--proto-redir": "SAFE",
    "--proxy": "HOP",
    "--proxy-anyauth": "SAFE",
    "--proxy-basic": "SAFE",
    "--proxy-ca-native": "SAFE",
    "--proxy-cacert": "TLS_MATERIAL",
    "--proxy-capath": "TLS_MATERIAL",
    "--proxy-cert": "TLS_MATERIAL",
    "--proxy-cert-type": "SAFE",
    "--proxy-ciphers": "SAFE",
    "--proxy-crlfile": "TLS_MATERIAL",
    "--proxy-digest": "SAFE",
    "--proxy-header": "SAFE",
    "--proxy-http2": "SAFE",
    "--proxy-insecure": "SAFE",
    "--proxy-key": "TLS_MATERIAL",
    "--proxy-key-type": "SAFE",
    "--proxy-negotiate": "SAFE",
    "--proxy-ntlm": "SAFE",
    "--proxy-pass": "SAFE",
    "--proxy-pinnedpubkey": "TLS_MATERIAL",
    "--proxy-service-name": "SAFE",
    "--proxy-ssl-allow-beast": "SAFE",
    "--proxy-ssl-auto-client-cert": "SAFE",
    "--proxy-tls13-ciphers": "SAFE",
    "--proxy-tlsauthtype": "SAFE",
    "--proxy-tlspassword": "SAFE",
    "--proxy-tlsuser": "SAFE",
    "--proxy-tlsv1": "SAFE",
    "--proxy-user": "SAFE",
    "--proxy1.0": "HOP",
    "--proxytunnel": "SAFE",
    "--pubkey": "SAFE",
    "--quote": "SAFE",
    "--random-file": "SAFE",
    "--range": "SAFE",
    "--rate": "SAFE",
    "--raw": "SAFE",
    "--referer": "SAFE",
    "--remote-header-name": "SAFE",
    "--remote-name": "SAFE",
    "--remote-name-all": "SAFE",
    "--remote-time": "SAFE",
    "--remove-on-error": "SAFE",
    "--request": "SAFE",
    "--request-target": "SAFE",
    "--resolve": "HOP",
    "--retry": "SAFE",
    "--retry-all-errors": "SAFE",
    "--retry-connrefused": "SAFE",
    "--retry-delay": "SAFE",
    "--retry-max-time": "SAFE",
    "--sasl-authzid": "SAFE",
    "--sasl-ir": "SAFE",
    "--service-name": "SAFE",
    "--show-error": "SAFE",
    "--silent": "SAFE",
    "--socks4": "HOP",
    "--socks4a": "HOP",
    "--socks5": "HOP",
    "--socks5-basic": "SAFE",
    "--socks5-gssapi": "SAFE",
    "--socks5-gssapi-nec": "SAFE",
    "--socks5-gssapi-service": "SAFE",
    "--socks5-hostname": "HOP",
    "--speed-limit": "SAFE",
    "--speed-time": "SAFE",
    "--ssl": "SAFE",
    "--ssl-allow-beast": "SAFE",
    "--ssl-auto-client-cert": "SAFE",
    "--ssl-no-revoke": "SAFE",
    "--ssl-reqd": "SAFE",
    "--ssl-revoke-best-effort": "SAFE",
    "--sslv2": "SAFE",
    "--sslv3": "SAFE",
    "--stderr": "MIRROR",
    "--styled-output": "SAFE",
    "--suppress-connect-headers": "SAFE",
    "--tcp-fastopen": "SAFE",
    "--tcp-nodelay": "SAFE",
    "--telnet-option": "SAFE",
    "--tftp-blksize": "SAFE",
    "--tftp-no-options": "SAFE",
    "--time-cond": "SAFE",
    "--tls-max": "SAFE",
    "--tls13-ciphers": "SAFE",
    "--tlsauthtype": "SAFE",
    "--tlspassword": "SAFE",
    "--tlsuser": "SAFE",
    "--tlsv1": "SAFE",
    "--tlsv1.0": "SAFE",
    "--tlsv1.1": "SAFE",
    "--tlsv1.2": "SAFE",
    "--tlsv1.3": "SAFE",
    "--tr-encoding": "SAFE",
    "--trace": "MIRROR",
    "--trace-ascii": "MIRROR",
    "--trace-config": "MIRROR",
    "--trace-ids": "MIRROR",
    "--trace-time": "MIRROR",
    "--unix-socket": "HOP",
    "--upload-file": "SAFE",
    "--url": "DEST",
    "--url-query": "SAFE",
    "--use-ascii": "SAFE",
    "--user": "SAFE",
    "--user-agent": "SAFE",
    "--variable": "SAFE",
    "--verbose": "MIRROR",
    "--version": "TERMINAL",
    "--write-out": "SAFE",
    "--xattr": "SAFE",
}

# --------------------------------------------------------------------------
# SHORT_TO_LONG: every short-opt letter curl defines, mapped to its long
# name (arity/role always looked up via the long name). Source: each long
# option's own "short" field in the oracle -- curl defines no short-only
# option with no long counterpart.
# --------------------------------------------------------------------------
SHORT_TO_LONG = {
    "#": "--progress-bar",
    "0": "--http1.0",
    "1": "--tlsv1",
    "2": "--sslv2",
    "3": "--sslv3",
    "4": "--ipv4",
    "6": "--ipv6",
    ":": "--next",
    "A": "--user-agent",
    "B": "--use-ascii",
    "C": "--continue-at",
    "D": "--dump-header",
    "E": "--cert",
    "F": "--form",
    "G": "--get",
    "H": "--header",
    "I": "--head",
    "J": "--remote-header-name",
    "K": "--config",
    "L": "--location",
    "M": "--manual",
    "N": "--no-buffer",
    "O": "--remote-name",
    "P": "--ftp-port",
    "Q": "--quote",
    "R": "--remote-time",
    "S": "--show-error",
    "T": "--upload-file",
    "U": "--proxy-user",
    "V": "--version",
    "X": "--request",
    "Y": "--speed-limit",
    "Z": "--parallel",
    "a": "--append",
    "b": "--cookie",
    "c": "--cookie-jar",
    "d": "--data",
    "e": "--referer",
    "f": "--fail",
    "g": "--globoff",
    "h": "--help",
    "i": "--include",
    "j": "--junk-session-cookies",
    "k": "--insecure",
    "l": "--list-only",
    "m": "--max-time",
    "n": "--netrc",
    "o": "--output",
    "p": "--proxytunnel",
    "q": "--disable",
    "r": "--range",
    "s": "--silent",
    "t": "--telnet-option",
    "u": "--user",
    "v": "--verbose",
    "w": "--write-out",
    "x": "--proxy",
    "y": "--speed-time",
    "z": "--time-cond",
}

# --------------------------------------------------------------------------
# Category cross-check data (curl's own --help proxy/dns/connection groupings
# -- `--help all`'s section headers, not this module's own role names).
# Used only by the completeness/soundness guard in
# tests/test_curlgrammar.py: every option in one of these three categories
# that this module does NOT mark HOP must appear in
# `_PROXY_DNS_CONN_SAFE_JUSTIFIED` below.
# --------------------------------------------------------------------------
_CATEGORY_PROXY = frozenset(
    {
        "--anyauth",
        "--digest",
        "--haproxy-clientip",
        "--haproxy-protocol",
        "--noproxy",
        "--preproxy",
        "--proxy",
        "--proxy-anyauth",
        "--proxy-basic",
        "--proxy-cacert",
        "--proxy-capath",
        "--proxy-cert",
        "--proxy-cert-type",
        "--proxy-ciphers",
        "--proxy-crlfile",
        "--proxy-digest",
        "--proxy-header",
        "--proxy-http2",
        "--proxy-insecure",
        "--proxy-key",
        "--proxy-key-type",
        "--proxy-negotiate",
        "--proxy-ntlm",
        "--proxy-pass",
        "--proxy-pinnedpubkey",
        "--proxy-service-name",
        "--proxy-ssl-allow-beast",
        "--proxy-ssl-auto-client-cert",
        "--proxy-tls13-ciphers",
        "--proxy-tlsauthtype",
        "--proxy-tlspassword",
        "--proxy-tlsuser",
        "--proxy-tlsv1",
        "--proxy-user",
        "--proxy1.0",
        "--proxytunnel",
        "--socks4",
        "--socks4a",
        "--socks5",
        "--socks5-basic",
        "--socks5-gssapi",
        "--socks5-gssapi-nec",
        "--socks5-gssapi-service",
        "--socks5-hostname",
        "--suppress-connect-headers",
    }
)
_CATEGORY_DNS = frozenset(
    {
        "--dns-interface",
        "--dns-ipv4-addr",
        "--dns-ipv6-addr",
        "--dns-servers",
        "--doh-cert-status",
        "--doh-insecure",
        "--doh-url",
        "--ipv4",
        "--ipv6",
        "--resolve",
    }
)
_CATEGORY_CONNECTION = frozenset(
    {
        "--abstract-unix-socket",
        "--connect-timeout",
        "--connect-to",
        "--continue-at",
        "--happy-eyeballs-timeout-ms",
        "--interface",
        "--ipv4",
        "--ipv6",
        "--keepalive-time",
        "--limit-rate",
        "--local-port",
        "--max-filesize",
        "--max-time",
        "--no-keepalive",
        "--parallel",
        "--parallel-immediate",
        "--parallel-max",
        "--proto",
        "--proto-default",
        "--proto-redir",
        "--rate",
        "--request",
        "--resolve",
        "--speed-limit",
        "--speed-time",
        "--tcp-fastopen",
        "--tcp-nodelay",
        "--unix-socket",
    }
)

# Every VALUE-taking option in the three categories above that this module
# does NOT mark HOP -- each is here because its value cannot redirect curl's
# own request to a different remote host/hop:
#   --noproxy: DISABLES proxying for matching hosts -- reduces hop surface,
#     never adds one.
#   --*-timeout/--*-time/--max-filesize/--limit-rate/--rate/--parallel-max/
#     --keepalive-time/--continue-at: numeric limits/offsets, not hosts.
#   --interface/--local-port: choose the LOCAL outbound interface/port, never
#     the remote destination.
#   --proto/--proto-default/--proto-redir: restrict/assume a URL SCHEME, not
#     a host; this module's own https:// requirement (decision 2) already
#     covers the scheme axis directly against the DEST word's literal text.
#   --request: the HTTP method string (GET/POST/...), not a host.
#   --proxy-cacert/--proxy-capath/--proxy-cert/--proxy-crlfile/--proxy-key/
#     --proxy-pinnedpubkey: TLS_MATERIAL role already (see OPTION_ROLE) --
#     also proxy-category, listed here too since this set is a plain
#     "not-HOP" membership check, not mutually exclusive with TLS_MATERIAL.
#   --proxy-cert-type/--proxy-key-type/--proxy-ciphers/--proxy-tls13-ciphers/
#     --proxy-service-name/--proxy-tlsauthtype/--proxy-tlspassword/
#     --proxy-tlsuser/--proxy-pass/--proxy-user/--socks5-gssapi-service/
#     --proxy-header: auth/algorithm/service-name STRINGS for a proxy or
#     SOCKS5 connection that is only ever reached through an actual
#     --proxy/--socks5/... flag -- which independently carries the HOP role
#     and refuses the exemption unconditionally. These values are inert
#     without a HOP flag also present on the line.
#   --haproxy-clientip: sets the client IP reported *to* the origin via the
#     PROXY protocol header -- describes the client, not a destination.
_PROXY_DNS_CONN_SAFE_JUSTIFIED = frozenset(
    {
        "--connect-timeout",
        "--continue-at",
        "--happy-eyeballs-timeout-ms",
        "--haproxy-clientip",
        "--interface",
        "--keepalive-time",
        "--limit-rate",
        "--local-port",
        "--max-filesize",
        "--max-time",
        "--noproxy",
        "--parallel-max",
        "--proto",
        "--proto-default",
        "--proto-redir",
        "--proxy-cacert",
        "--proxy-capath",
        "--proxy-cert",
        "--proxy-cert-type",
        "--proxy-ciphers",
        "--proxy-crlfile",
        "--proxy-header",
        "--proxy-key",
        "--proxy-key-type",
        "--proxy-pass",
        "--proxy-pinnedpubkey",
        "--proxy-service-name",
        "--proxy-tls13-ciphers",
        "--proxy-tlsauthtype",
        "--proxy-tlspassword",
        "--proxy-tlsuser",
        "--proxy-user",
        "--rate",
        "--request",
        "--socks5-gssapi-service",
        "--speed-limit",
        "--speed-time",
    }
)


def option_role(long_name: str) -> str:
    """Role for *long_name* (must be an exact key of OPTION_ROLE -- prefix
    resolution is curlargv.py's job, not this accessor's)."""
    return OPTION_ROLE[long_name]


def option_arity(long_name: str) -> str:
    """"bool" or "value" for *long_name* (exact key of OPTION_ARITY)."""
    return OPTION_ARITY[long_name]
